name: Deploy Nginx

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      REGION: us-central1
      SERVICE_NAME: nginx-service
      IMAGE_URL: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/nginx

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar o gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build e Push da imagem Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t $IMAGE_URL:latest .
        docker push $IMAGE_URL:latest

    - name: Deploy no Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE_URL:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated
